api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  id = "renku/conda-nodefaults"
  name = "Conda nodefaults buildpack"
  version = "0.9.1"
