description = "CUDA enabled builder for Renku frontends and environments."

[[buildpacks]]
  uri = "../../buildpacks/renku-variables"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/vscodium"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/conda-nodefaults"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/kernel-installer"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/jupyterlab"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/ttyd"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/custom-frontend"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/python-dependency-manager"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/renv"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/r-dependency-manager"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/rstudio"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/init-scripts"
  version = "0.9.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/python:2.55.0"
  version = "2.55.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/miniconda:0.11.22"
  id = "paketo-buildpacks/miniconda"
  version = "0.11.22"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/node-engine:8.1.1"
  id = "paketo-buildpacks/node-engine"
  version = "8.1.1"

[[buildpacks]]
  uri = "docker://docker.io/heroku/buildpack-deb-packages:0.2.0"
  id = "heroku/deb-packages"
  version = "0.2.0"

[[buildpacks]]
  uri = "../../buildpacks/homebrew"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/r-conda"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/coding-agent"
  version = "0.9.0"

[[buildpacks]]
  uri = "../../buildpacks/r-dependency-manager-conda"
  version = "0.9.0"

[[order]]

  [[order.group]]
    id = "renku/conda-nodefaults"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.11.22"

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.55.0"

  [[order.group]]
    id = "renku/python-dependency-manager"
    version = "0.9.0"

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "renku/jupyterlab"
    version = "0.9.0"

  [[order.group]]
    id = "renku/kernel-installer"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[[order]]

  [[order.group]]
    id = "renku/conda-nodefaults"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.55.0"

  [[order.group]]
    id = "renku/python-dependency-manager"
    version = "0.9.0"

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "renku/custom-frontend"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[[order]]

  [[order.group]]
    id = "renku/conda-nodefaults"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.55.0"

  [[order.group]]
    id = "renku/python-dependency-manager"
    version = "0.9.0"

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "renku/ttyd"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[[order]]

  [[order.group]]
    id = "renku/conda-nodefaults"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/python"
    version = "2.55.0"

  [[order.group]]
    id = "renku/python-dependency-manager"
    version = "0.9.0"

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "renku/vscodium"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[[order]]

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.11.22"

  [[order.group]]
    id = "renku/r-conda"
    version = "0.9.0"

  [[order.group]]
    id = "renku/renv"
    version = "0.9.0"

  [[order.group]]
    id = "renku/r-dependency-manager"
    version = "0.9.0"

  [[order.group]]
    id = "renku/rstudio"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[[order]]

  [[order.group]]
    id = "renku/conda-nodefaults"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.11.22"

  [[order.group]]
    id = "renku/r-dependency-manager-conda"
    version = "0.9.0"

  [[order.group]]
    id = "renku/rstudio"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[[order]]

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.11.22"

  [[order.group]]
    id = "renku/r-conda"
    version = "0.9.0"

  [[order.group]]
    id = "renku/renv"
    version = "0.9.0"

  [[order.group]]
    id = "renku/r-dependency-manager"
    version = "0.9.0"

  [[order.group]]
    id = "renku/custom-frontend"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[[order]]

  [[order.group]]
    id = "renku/conda-nodefaults"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/renku-variables"
    version = "0.9.0"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.11.22"

  [[order.group]]
    id = "renku/r-dependency-manager-conda"
    version = "0.9.0"

  [[order.group]]
    id = "renku/custom-frontend"
    version = "0.9.0"

  [[order.group]]
    id = "heroku/deb-packages"
    version = "0.2.0"
    optional = true

  [[order.group]]
    id = "renku/homebrew"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "renku/init-scripts"
    version = "0.9.0"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "8.1.1"
    optional = true

  [[order.group]]
    id = "renku/coding-agent"
    version = "0.9.0"
    optional = true

[build]
  image = "ghcr.io/swissdatasciencecenter/renku-frontend-buildpacks/cuda-build-image:0.9.0"

  [[build.env]]
    name = "BP_RENKU_FRONTENDS"
    value = "vscodium"

[run]

  [[run.images]]
    image = "ghcr.io/swissdatasciencecenter/renku-frontend-buildpacks/cuda-run-image:0.9.0"
    mirrors = []

[lifecycle]
  version = "0.20.19"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
