api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  description = "A simple buildpack that allows the user to define init scripts"
  id = "renku/init-scripts"
  name = "init scripts runner buildpack"
  version = "0.9.1"
