api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  id = "renku/kernel-installer"
  name = "jupyter kernel installer"
  version = "0.9.0"
