api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  id = "renku/renku-variables"
  name = "Renku Environment Variables"
  version = "0.9.1"
