api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  description = "A simple buildpack that requires the dependency manager for python"
  id = "renku/python-dependency-manager"
  name = "python dependency manager buildpack"
  version = "0.9.1"
