api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  description = "A buildpack that installs homebrew packages from a Brewfile."
  id = "renku/homebrew"
  name = "homebrew buildpack"
  version = "0.9.1"
