api = "0.11"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"

[buildpack]
  description = "A simple buildpack that provides the dependency manager for r"
  id = "renku/r-dependency-manager"
  name = "r dependency manager buildpack"
  version = "0.9.0"
